### ISSUE TITLE
[Feature Request] Remote JupyterLab support

### ISSUE THREAD

**Issue by shurensha** [benlubas/molten-nvim#215]
Can you please add support for remote jupyter lab server? so the only inputs are the url and port? Thank you very much

**Comment by benlubas** [comment]
Checkout [remote-hosts](https://github.com/benlubas/molten-nvim/blob/main/docs/Advanced-Functionality.md#remote-hosts).

You can create a lua function that takes the url and port, writes a connection file to `/tmp/whatever` and then runs `:MoltenInit /tmp/whatever`

Or I'd be open to a PR that adds something similar. I just don't currently have a good way to test this

**Comment by shurensha** [comment]
i hope we can hide the kernels and instead rely on jupyter lab to manage the kernels

**Comment by benlubas** [comment]
If you want jupyter lab to manage the kernel then you have to start the kernel from jupyter lab (afaik). And still read remote-hosts so that you can connect.

**Comment by opqrstuvcut** [comment]
@shurensha 
This fork might be helpful (although it sometimes behaves buggy):
https://github.com/opqrstuvcut/molten-nvim/tree/feature/add_jupyterapi_runtime

You can connect to a kernel started with the jupyter lab command as follows:
:MoltenInit http://localhost:8888

**Comment by benlubas** [comment]
@opqrstuvcut definitely open a PR, would be happy to add this functionality.

What's the buggy behavior currently?

**Comment by opqrstuvcut** [comment]
@benlubas 
Thank you for your interest.

The bugs are as follows:
* Sometimes, the "Kernel xxx is ready" message does not appear unless some code is executed after running MoltenInit.
* If you execute MoltenEvaluateCell immediately after running MoltenInit, the standard output may not display correctly (however, if you wait some time and then run MoltenEvaluateCell, it works as expected).

I plan to submit a PR once these issues are fixed, but since they don't cause significant problems for personal use, addressing these bugs has been postponed.
