### ISSUE TITLE
Unable to create environment specific Kernels

### ISSUE THREAD

**Issue by t-ober** [benlubas/molten-nvim#238]
After running `MoltenInit` I get prompted which kernel to launch. 

I have three options:
1: project_name
2: rust
3: mojo-jupyter-kernel

1 seems to be what I want. 
Although i suggest it should be a variable that get's replaced by the actual current project name.
It runs the kernel specified in `~/Library/Jupyter/kernels/project_name`

`~/Library/Jupyter/kernels/project_name/kernel.json` stores the interpreter to use:

```json
{
  "argv": [
    "/Users/thomas/.virtualenvs/pymolten/bin/python",
    "-Xfrozen_modules=off",
    "-m",
    "ipykernel_launcher",
    "-f",
    "{connection_file}"
  ],
  "display_name": "project_name",
  "language": "python",
  "metadata": {
    "debugger": true
  }
}
```

For any other projects my only option is to use this `project_name` interpreter again which is not what I want.
This happens also when I start with a different activated venv
```
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- pyenv: Path: /Users/thomas/.pyenv/libexec/pyenv
- pyenv: Root: /Users/thomas/.pyenv
- Using: g:python3_host_prog = "/Users/thomas/.virtualenvs/neovim/bin/python3"
- Executable: /Users/thomas/.virtualenvs/neovim/bin/python3
- Python version: 3.11.4
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- $VIRTUAL_ENV is set to: /Users/thomas/.virtualenvs/foo
- Python version: 3.11.9
- OK $VIRTUAL_ENV provides :!python.

```

Am I missing something? How can I create project specific kernels that use the actual activated virtual environments?

**Comment by benlubas** [comment]
I actually wasn't to sure of how to answer this. My initial thought was that kernels are installed per user, and capture the current environment when they're installed. It seems like this is mostly correct. I found this forum post that elaborates a bit.

https://discourse.jupyter.org/t/what-is-the-relationship-between-kernels-and-virtual-environments/10293

As far as kernels that match your current venv, I'm not really sure there's an easy way to do that right now. You might have some luck with running `jupyter kernel` from your venv and attaching to that. If that works, you could write a lua script that uses vim.system to do it for you and initialize molten with the result.

If I wanted project specific kernels I'd use a nix shell, but that's really overkill for most cases. I also don't have an example, sorry.

---

In any case, if you figure out a good way to do it please leave an update, I'm sure others will be curious.

**Comment by rltq** [comment]
I'm currently in the process of setting up Molten and figuring out how to connect the Jupyter kernel automatically in Anaconda. So I could miss some details. Did you check [this](https://github.com/benlubas/molten-nvim/blob/92b2599ef813b188391d5f00f5f94ce22ecd2598/docs/Notebook-Setup.md?plain=1#L275) guide? This code is about detecting kernel by molten itself.
 
As far as I understand, what @t-ober wants  is that the kernel automatically switches as project changes. (unsure the scope of 'project' meant) In my opinion, if you want molten to find kernel that matches current venv, you can bypass by [installing Jupyter kernel as same as virtual environment name](https://github.com/benlubas/molten-nvim/blob/92b2599ef813b188391d5f00f5f94ce22ecd2598/docs/Virtual-Environments.md?plain=1#L60).

```bash
$ (project name) python -m ipykernel install --user --name {project name}
```

![image](https://github.com/user-attachments/assets/c1abfb39-07ad-4f16-978d-09f684850b64)
<p align=center><sup>in the image, I'm in the venv named: molten</sup></p>

As benlubas mentioned, molten is detecting *current user env*. In my limited knowledge, molten activates the kernel by [its name](https://github.com/benlubas/molten-nvim/blob/92b2599ef813b188391d5f00f5f94ce22ecd2598/rplugin/python3/molten/runtime.py#L257). 
Activating and setting up each venv in each project are time-consuming, but like I mentioned, registering kernels that matches to virtual environment name is the easiest way. Otherwise, molten might use paths of kernel, yet it looks hard-coded way. So naming venv as a project name (or related name) would help. At least, it could save time of checking current venv.

VisualStudioCode control every interpreter so that can easily switch kernels without changing venv. I hope molten can do so, but I agree with benlubas's opinion. It is too much for ordinary cases.

Hope this will be considered a proper comment.

**Comment by t-ober** [comment]
Sorry, I was on the road for a few days. 

As usual this was pretty much a me problem: 

I somehow messed up the kernel creation for my different virtual environment via the: 
`$ (project name) python -m ipykernel install --user --name {project name}`
command.

Therefore i couldn't initialize the kernel with that associated environment and could only fall back on the original kernel, which had the wrong associated environment. 

Thanks both of you!!!  🙂
